BOARD      = mega2560
ARDUINODIR = /usr/share/arduino
TARGET     = build/output

SOURCES:= src/main.cpp src/registers.cpp src/encoder.cpp src/controller.cpp
LIBRARIES:= SoftwareSerial Servo Wire

include Arduino.mk
